const fs = require('fs');

const mockCandidates = `
export const MOCK_CANDIDATES: CandidateProfile[] = [
  {
    ...EMPTY_PROFILE,
    id: 'cand-1',
    createdAt: '16 Jul 2026',
    firstName: 'sathyaraj',
    lastName: '',
    dateOfBirth: '1986-07-19',
    mobileNumber: '9003628412',
    passportAvailable: 'Yes',
    jobPreference: 'N/A',
    countryLookingFor: 'Singapore',
    serviceChargesStatus: 'Need Time',
    assignedToHR: 'Hajira',
    interestLevel: 'Somewhat Interested',
    whatsappNumber: '',
  },
  {
    ...EMPTY_PROFILE,
    id: 'cand-2',
    createdAt: '16 Jul 2026',
    firstName: 'Deepan',
    lastName: '',
    dateOfBirth: '1990-09-05',
    mobileNumber: '9080482747',
    passportAvailable: 'Yes',
    jobPreference: 'Western Food',
    countryLookingFor: 'Singapore',
    serviceChargesStatus: 'Agreed',
    assignedToHR: 'Sharmila',
    interestLevel: 'Interested',
    whatsappNumber: '',
  },
  {
    ...EMPTY_PROFILE,
    id: 'cand-3',
    createdAt: '16 Jul 2026',
    firstName: 'Vignesh',
    lastName: '',
    dateOfBirth: '1990-10-01',
    mobileNumber: '8778281353',
    passportAvailable: 'Yes',
    jobPreference: 'continental',
    countryLookingFor: 'Singapore',
    serviceChargesStatus: 'Agreed',
    assignedToHR: 'Sreya',
    interestLevel: 'Interested',
    whatsappNumber: '',
  },
  {
    ...EMPTY_PROFILE,
    id: 'cand-4',
    createdAt: '16 Jul 2026',
    firstName: 'Sathik',
    lastName: '',
    dateOfBirth: '1983-09-15',
    mobileNumber: '9585602933',
    passportAvailable: 'Yes',
    jobPreference: 'Briyani / North Indian',
    countryLookingFor: 'Singapore',
    serviceChargesStatus: 'Agreed',
    assignedToHR: 'Bakkia',
    interestLevel: 'Interested',
    whatsappNumber: '',
  },
  {
    ...EMPTY_PROFILE,
    id: 'cand-5',
    createdAt: '16 Jul 2026',
    firstName: 'ilakiyan',
    lastName: '',
    dateOfBirth: '1992-07-04',
    mobileNumber: '7695912313',
    passportAvailable: 'Yes',
    jobPreference: 'southcook/parotta/chinese',
    countryLookingFor: 'Singapore',
    serviceChargesStatus: 'Agreed',
    assignedToHR: 'Hajira',
    interestLevel: 'Interested',
    whatsappNumber: '',
  },
  {
    ...EMPTY_PROFILE,
    id: 'cand-6',
    createdAt: '16 Jul 2026',
    firstName: 'Mahadir',
    lastName: '',
    dateOfBirth: '1994-06-01',
    mobileNumber: '9790957915',
    passportAvailable: 'Yes',
    jobPreference: 'poratta master / chinese',
    countryLookingFor: 'Singapore',
    serviceChargesStatus: 'Agreed',
    assignedToHR: 'Sharmila',
    interestLevel: 'Interested',
    whatsappNumber: '',
  },
  {
    ...EMPTY_PROFILE,
    id: 'cand-7',
    createdAt: '15 Jul 2026',
    firstName: 'Elayaraja',
    lastName: '',
    dateOfBirth: '1989-05-04',
    mobileNumber: '9080752847',
    passportAvailable: 'Yes',
    jobPreference: 'All Rounder',
    countryLookingFor: 'Singapore',
    serviceChargesStatus: 'Agreed',
    assignedToHR: 'Sharmila',
    interestLevel: 'Interested',
    whatsappNumber: '',
  }
];
`;

let code = fs.readFileSync('src/mockData.ts', 'utf8');
code += mockCandidates;
fs.writeFileSync('src/mockData.ts', code);
console.log('Appended MOCK_CANDIDATES successfully');
